name: 'ğŸ“ Generate PDF from Markdown'

on:
  workflow_dispatch:

  push:
    paths:
      - 'docs/**'

jobs:
  generate-pdf:
    uses: nct-cherrypick/MarkdownToPDF/.github/workflows/GeneratePDF.yaml@main
    with:
      source-directory: './docs'
      output-directory: './dist'
      is-nest: true
